server:
  port: 9092

spring:
  # Spring JDBC configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/task
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:29092
