server:
  port: 8082

spring:
  # Spring JDBC configuration
  datasource:
    url: jdbc:postgresql://postgres:5432/task
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # Spring Data JPA configuration
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: group-id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
